version: "1.0.0-{build}"

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
test: off

build_script:
  - set K_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER% #temp
  - set K_BUILD_VERSION=%K_BUILD_VERSION:~-4%
  - build.cmd

artifacts:
  - path: artifacts\build\*.nupkg

